# Usa la imagen oficial de MySQL
FROM mysql:8.0

# Establece las variables de entorno para la configuración de la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mi_base_de_datos
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=contraseña

# Exponer el puerto en el que MySQL estará disponible
EXPOSE 3306
