# Usa la imagen oficial de phpMyAdmin
FROM phpmyadmin/phpmyadmin:latest

# Establece las variables de entorno para configurar phpMyAdmin
ENV PMA_HOST=nombre_del_contenedor_mysql
ENV PMA_PORT=3306

# Expone el puerto en el que phpMyAdmin estará disponible
EXPOSE 80
